### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by Predelnik** [vinntreus/BuildMonitor#12]
I don't think that anything except manifest needs to be changed so it would be cool if new VS version would be supported.

**Comment by vinntreus** [comment]
Well, I'll still need Visual Studio and be able to create a vsix package (which I upload to visual studio gallery). Currently I don't have access to such installment.

**Comment by Aleksanderis** [comment]
vsix manifest, whick worked for me (proper xml file attached):

`<Vsix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Version="1.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2010">
  <Identifier Id="d350a95e-5d09-4b5d-9075-0a5f7bb6b1dc">
    <Name>Build Monitor</Name>
    <Author>Daniel Vinntreus</Author>
    <Version>1.31</Version>
    <Description xml:space="preserve">Measure how long it takes to build your solution and individual projects in Visual Studio.</Description>
    <Locale>1033</Locale>
    <SupportedProducts>
      <VisualStudio Version="10.0">
        <Edition>Pro</Edition>
      </VisualStudio>
      <VisualStudio Version="11.0">
        <Edition>Pro</Edition>
      </VisualStudio>
      <VisualStudio Version="12.0">
        <Edition>Pro</Edition>
      </VisualStudio>
      <VisualStudio Version="14.0">
        <Edition>Pro</Edition>
      </VisualStudio>
    </SupportedProducts>
    <SupportedFrameworkRuntimeEdition MinVersion="4.5" />
  </Identifier>
  <Content>
    <VsPackage>|%CurrentProject%;PkgdefProjectOutputGroup|</VsPackage>
    <MefComponent>|%CurrentProject%|</MefComponent>
  </Content>
</Vsix>`

[extension.vsixmanifest.txt](https://github.com/vinntreus/BuildMonitor/files/45083/extension.vsixmanifest.txt)

Thanks for the nice extension by the way - helps me to optimize our big Visual Studion solution.:)

**Comment by VioletGiraffe** [comment]
You should just make a pull request with the updated file.
I'm not sure about the NuGet stuff, though. Can we leave it untouched?

**Comment by Aleksanderis** [comment]
I made a pull request, but then found out, that there is already one done for VS2015, but still not merged. The original owner just abandoned this solution, as well as .NET in general - at least what author mentioned himself. ;)

**Comment by VioletGiraffe** [comment]
Oh well, thanks for trying.

**Comment by vinntreus** [comment]
Fixed in https://github.com/vinntreus/BuildMonitor/pull/14
Have updated the package in Visual Studio Gallery as well: https://visualstudiogallery.msdn.microsoft.com/b0c87e47-f4ee-4935-9a59-f2c81ce692ab
